### ISSUE TITLE
Ensure best practices are followed and all models are updated in the repo with latest changes

### ISSUE THREAD

**Issue by abhishektvz** [credmark/credmark-models-py#115]
## Proposed change
Ensure best practices are being followed in the repo

## Why this is important
To improve maintainability and extensibility of the CMF models repo
 
## Additional context
Starting with a basic run through of all the models and checking if they are following best practices like: DTO declaration, code formatting

**Comment by kavitajoshi14** [comment]
@abhishektvz , in the curve_finance.py model where slug = "curve-fi.gauge-yield" , there is error in code.
![image](https://user-images.githubusercontent.com/98482866/171799443-e59b67a8-601b-4f69-8884-f72d579f1133.png)
and the error for this is:
![image](https://user-images.githubusercontent.com/98482866/171799601-e6507736-0617-489f-8829-4414bb0f1856.png)
