### ISSUE TITLE
[BUG] `sushiswap.get-pools` and `uniswap-v2.get-pools` have similar display names

### ISSUE THREAD

**Issue by robertkibet** [credmark/credmark-models-py#123]
**Describe the bug**

Seems like `sushiswap.get-pools` and `uniswap-v2.get-pools` slugs both seem to have the same `displayName`. is this intended?

**To Reproduce**

inspect response data from this endpoint: `https://gateway.credmark.com/v1/models`

**Expected behavior**
I believe both should have different `displayNames`

**Screenshots**
![image](https://user-images.githubusercontent.com/20405825/173349103-768928b9-3d9d-468c-8167-6459d07a4466.png)

**Comment by leafyoung** [comment]
updated in https://github.com/credmark/credmark-models-py/blob/c7f8051d7528dceef9efa74e987ddcb530035436/models/credmark/protocols/dexes/sushiswap/sushiswap.py#L44
