### ISSUE TITLE
[FEATURE]: Create fetcher model to fetch the data from FRAX APIs endpoints

### ISSUE THREAD

**Issue by CryticPun** [credmark/credmark-models-py#156]
**Is your feature request related to a problem? Please describe.**
Yes. I am using few FRAX api enpoints to get the data from frax finance and using that in FRAX PowerBI dashboard.
When i hit these endpoints (mentioned below) via browser, i can get data (in json format) returned without any need to authenticate.

1) https://api.frax.finance/pools
2) https://api.frax.finance/v1/amodata_v2/amo-allocations
3) https://api.frax.finance/combineddata

But when I am trying to fetch this data via automatic schedule in PowerBI online service, It 1st tries to authenticate the api and throws authentication error. This is causing issues for automatic shceuled data refresh for PowerBi Frax dashboard Report.

**Describe the solution you'd like**
as a work around to this issue, if we can get some data fetcher models created via CMF for these FRAX API endpoints, I can connect to those models in FRAX Dashboard and refresh the data without any error.
Note that PowerBI service is able to fetch and refresh the data from Credmark API without any issues.

**Describe alternatives you've considered**
If CMF based model creation is not possible, then we will have to consider creating few tables in Snowflake which can host and refresh the latest data from these API endpoints.

**Additional context**
This is an urgent request, as we are about to integrate FRAX dashboard in Credmark Terminal, and hence ensuring automatic data refresh is important.

**Comment by leafyoung** [comment]
Duplicated to https://github.com/credmark/Analytics/issues/2.
