### ISSUE TITLE
Credmark-dev shows zero loaded models

### ISSUE THREAD

**Issue by nishgaba-ai** [credmark/credmark-models-py#2]
Credmark-dev command runs successfully but shows zero loaded models.
<img width="944" alt="load-models" src="https://user-images.githubusercontent.com/30121375/154931956-75ba83b0-af7f-4536-b4b5-0fe0b63c2ed4.png">

**Comment by iwyrkore** [comment]
@nishgaba-ai Is this resolved now? If so, we can close it.
