### ISSUE TITLE
Price data sources should be 'dex' or 'cex'

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-models-py#207]
We agreed that price data sources would either be 'dex' or 'cex'. Those are the only values that should be returned in the "protocol" field and the only values that should be accepted for the "src" parameter.

I've updated the documentation accordingly. 

@leafyoung could you please make sure that those are the values that the model returns? 

@v1nvn I wonder if the result field shouldn't be "src" instead of "protocol" so that it mirrors the request.

**Comment by murphy** [comment]
FYI: https://docs.credmark.com/token-api-concepts/prices/controlling-the-price-source

**Comment by leafyoung** [comment]
Completed 
https://github.com/credmark/credmark-gateway-api/actions/runs/3144112588

- cex
![image](https://user-images.githubusercontent.com/214410/192797914-f9611a4e-356d-458c-a235-633f0272e4fe.png)

- dex
![image](https://user-images.githubusercontent.com/214410/192798010-9dd971b1-ebb8-473e-bb85-bb6ffaa5ac0d.png)
