### ISSUE TITLE
Configure environment variables

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-models-py#23]
I found this section confusing because it's not clear that this is only needed for local development. It should be stated that once a model is running in Credmark's infra, it will have access to Credmark's node infrastructure. 

Also, I don't know if it should be stated that, in future, we may host our own node and give people automatic throttled access to it if they don't configure one explicitly.

**Comment by CryticPun** [comment]
@murphy 
This is a kind of mandatory step even to run (consume) models as few of models require web3 data. And that data is fetched via url mentioned in .env file.
the last line of this section mentions:
"This variable is used to run models which require web3. It can be ignored for those models which do not require web3."

On the point of hosting node and giving people direct access to web3 provider interface, once we have that infrastructure up and running, we can mark this steps as optional and provide more then. 
To be frank, I actually added that detail earlier while preparing the initial draft of document but later on was dropped during review process as it made more sense to only include detail of current state of framework.

**Comment by iwyrkore** [comment]
Updated docs.
