### ISSUE TITLE
Getting this error on mac machine while running sdk

### ISSUE THREAD

**Issue by Deadsec69** [credmark/credmark-models-py#41]
credmark.cmf.engine.model_loader - ERROR - Error loading manifest for module models.examples.historical_examples in model file models/examples/historical_examples.py: No module named '_bz2'

**Comment by murphy** [comment]
@Deadsec69 are you using the credmark-dev utility or the new client SDK?

**Comment by Deadsec69** [comment]
@murphy I was using credmark-dev but I found a solution for the above just needed to run the command 
brew install bzip2
