### ISSUE TITLE
Proxy contract loading

### ISSUE THREAD

**Issue by leafyoung** [credmark/credmark-models-py#48]
1. Changed proxy address

As of block 13432143, the Comptroller of Compound 0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b was proxied by
- Our DB: 0xbafe01ff935c7305907c33bf824352ee5979b526
- Actual: 0x234B619B4f4E405665F7d94F2CE60c24256032B5

> https://etherscan.io/address/0x3d9819210a31b4961b30ef54be2aed79b9c9cd3b#readProxyContract
> ABI for the implementation contract at [0xbafe01ff935c7305907c33bf824352ee5979b526]
> Previously recorded to be on [0x234b619b4f4e405665f7d94f2ce60c24256032b5]

`credmark-dev run compound-v2.get-pools --input '{}' -l compound-v2.get-pool-info -b 13432143 --format_json`

2. Many aTokens are not recognized as proxy in Etherscan. 

https://etherscan.io/address/0xfe8f19b17ffef0fdbfe2671f248903055afaa8ca/advanced#code

`Token(address='0xfe8f19b17ffef0fdbfe2671f248903055afaa8ca').is_transparent_proxy`

3. Wrong ABI loaded

```
token = Token(address='0xca823F78C2Dd38993284bb42Ba9b14152082F7BD')
token.functions.getSupplyData().call()  # Error ABI, staple ERC20 was loaded.

token = Token(address='0xca823F78C2Dd38993284bb42Ba9b14152082F7BD')
token._meta.abi = AAVE_STABLEDEBT_ABI # Impose an ABI for stable debt
token.functions.getSupplyData().call()
```

https://etherscan.io/address/0xca823F78C2Dd38993284bb42Ba9b14152082F7BD#code

**Comment by iwyrkore** [comment]
@leafyoung Is this fixed now with that merge? Can we close it?

**Comment by leafyoung** [comment]
It has been (temporarily) fixed in https://github.com/credmark/credmark-models-py/pull/49. Close this for now.
More cleanup to be done in DB
- Proxy
- ABI
