### ISSUE TITLE
Missing ABI's for curve pools

### ISSUE THREAD

**Issue by mostarz93** [credmark/credmark-models-py#56]
Pools with this ABI will return balances: https://etherscan.io/address/0xd632f22692FaC7611d2AA1C0D552930D43CAEd3B#readContract

Pools with this ABI will NOT return balances: https://etherscan.io/address/0x94e131324b6054c0D789b190b2dAC504e4361b53#readContract

**Comment by leafyoung** [comment]
Re-produced here

`credmark-dev run curve-fi.pool-info -i '{"address":"0xd632f22692FaC7611d2AA1C0D552930D43CAEd3B"}' -j`

```
 "balances": [
            1597830156357033034180157434,
            1135964478378786160228991343
        ],
        "underlying_tokens": {
            "tokens": []
        },
        "A": 1500,
        "name": "Curve.fi Factory USD Metapool: Frax"
```

`credmark-dev run curve-fi.pool-info -i '{"address":"0x94e131324b6054c0D789b190b2dAC504e4361b53"}' -j`
```
    "output": {
        "address": "0x94e131324b6054c0d789b190b2dac504e4361b53",
        "virtualPrice": 1000000000000000000,
        "tokens": {
            "tokens": []
        },
        "balances": [],
        "underlying_tokens": {
            "tokens": []
        },
        "A": 0,
        "name": "Curve.fi UST/3Crv"
    },
```
